"""add post model

Revision ID: 018581ea3a21
Revises: fcb983a6e426
Create Date: 2022-03-29 13:58:47.641232

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '018581ea3a21'
down_revision = 'fcb983a6e426'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=50), nullable=False),
    sa.Column('subHeading', sa.String(length=100), nullable=True),
    sa.Column('body', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('heading')
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###

