"""remove user comment relations

Revision ID: 2c7b17f5fa1b
Revises: e618a4c4c818
Create Date: 2022-04-12 13:14:07.861870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c7b17f5fa1b'
down_revision = 'e618a4c4c818'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_ibfk_2', 'comments', type_='foreignkey')
    op.drop_column('comments', 'user_id')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('comments_ibfk_2', 'comments', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###

