"""add datetime

Revision ID: 47a33cac2f05
Revises: 018581ea3a21
Create Date: 2022-03-29 18:43:47.119469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47a33cac2f05'
down_revision = '018581ea3a21'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('dateCreated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'dateCreated')
    # ### end Alembic commands ###

