"""comment md format

Revision ID: b3a1777fbfac
Revises: 3cc8065755be
Create Date: 2022-04-12 17:10:46.115324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3a1777fbfac'
down_revision = '3cc8065755be'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment_html', sa.Text(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'comment_html')
    # ### end Alembic commands ###

